template = "https://github.com/giellalt/template-lang-und"
rev_id = 128
template_sha = "d3822979aa3293c4fa535cdebe16b2b39ffde39f"

[replacements]
__REPO__ = "lang-sma"
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"
