template = "https://github.com/giellalt/template-lang-und"
rev_id = 49
template_sha = "f49176cce30fc7f3847ece4f27141f05cdb8d82f"

[replacements]
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"
