template = "https://github.com/giellalt/template-lang-und"
rev_id = 63
template_sha = "e3213f13f16fa63ed7d0ef4ac449bf559003fe0d"

[replacements]
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"
