template = "https://github.com/giellalt/template-lang-und"
rev_id = 230
template_sha = "f93135dcd0289587f23ccda4a615f9d6f4abe835"

[replacements]
__REPO__ = "lang-sma"
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"
