template = "https://github.com/giellalt/template-lang-und"
rev_id = 151
template_sha = "52213ce4ca8d6057a7e2ada1b6e2b79a11ebd004"

[replacements]
__REPO__ = "lang-sma"
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"
