template = "https://github.com/giellalt/template-lang-und"
rev_id = 46
template_sha = "c677c9c2d8798836673f39879fb4b666c603a765"

[replacements]
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"
