template = "https://github.com/giellalt/template-lang-und"
rev_id = 21
template_sha = "154d5af040a01f26add300ff42e21e0ffd28fb7b"

[replacements]
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"
