template = "https://github.com/giellalt/template-lang-und"
rev_id = 99
template_sha = "005ab3eef53b57ae6e87aa8645d004418a358350"

[replacements]
__REPO__ = "lang-sma"
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"
