template = "https://github.com/giellalt/template-lang-und"
rev_id = 85
template_sha = "9ed3df3b4a68b795ab2c3d59873602b657210547"

[replacements]
__REPO__ = "lang-sma"
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"
