template = "https://github.com/giellalt/template-lang-und"
rev_id = 239
template_sha = "0ad4d24907fe48e56692e2c8d2ac749fd207326c"

[replacements]
__REPO__ = "lang-sma"
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"
