template = "https://github.com/giellalt/template-lang-und"
rev_id = 185
template_sha = "ab0921ee1e75a04739e82be4750888e8da80f1db"

[replacements]
__REPO__ = "lang-sma"
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"
