template = "https://github.com/giellalt/template-lang-und"
rev_id = 204
template_sha = "8eab0289bf8affc67c3fd50e60d031c9ba59c3e5"

[replacements]
__REPO__ = "lang-sma"
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"

