template = "https://github.com/giellalt/template-lang-und"
rev_id = 236
template_sha = "acd43bc6e0438d4f0577a006ba3e1570aa4e1ecb"

[replacements]
__REPO__ = "lang-sma"
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"
