template = "https://github.com/giellalt/template-lang-und"
rev_id = 94
template_sha = "394256fcef9a3b6e16ef5ca9f975cf674be26544"

[replacements]
__REPO__ = "lang-sma"
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"
