template = "https://github.com/giellalt/template-lang-und"
rev_id = 259
template_sha = "dbafdbc00bdeb17f80ec54b2fd5d6ae330f25f51"

[replacements]
__GLOTTOLOG_ID__ = "sout2674"
__REPO__ = "lang-sma"
__UND2C__ = "sma"
__UNDEFINED__ = "South SÃ¡mi"
__UND__ = "sma"
